### PR TITLE
fix: support `--no-bundle` arg, add the built bin

### LINKED ISSUE #302: Adding portable build alongside with installers
When tauri builds an app, it also generates a portable build executable that you can just double click open (src-tauri/release/appname). 
It would be easier if tauri actions can release these builds as well so that devs can test the application before installing. 

it's fine if they don't check if webview is installed/available or even autoupdater doesn't work, as these will be mostly quick testing purpose.

### PR DESCRIPTION
**Pull request by jarjk**
add `--no-bundle`d artifacts

pov: "21 force pushes later, you realise the code is a lot like a spaghetti"

excellent tool though

quite neat this PR is, windows is bundled, macos and linux ran with `pnpm tauri build --no-bundle`

Screenshot 2025-09-30 at 20 57 11

### CODE REVIEW

File: src/build.ts [hunk 1]
```diff
@@ -214,6 +222,14 @@ export async function buildProject(
...
             version: app.version,
           }),
+          createArtifact({
+            path: join(artifactsPath, `${app.name}.exe`),
+            name: app.name,
+            debug,
+            platform: targetInfo.platform,
+            arch,
+            version: app.version,
+          }),
```
Comment (FabianLars) [inline src/build.ts]: This will be executed for every msi language which isn't good. you can move this into the winArtifacts.push call further down that also pushes the nsis installer.

File: src/build.ts [hunk 2]
```diff
@@ -265,6 +281,14 @@ export async function buildProject(
...
           version: app.version,
         }),
+        createArtifact({
+          path: join(artifactsPath, `${app.name}.exe`),
+          name: app.name,
+          debug,
+          platform: targetInfo.platform,
+          arch,
+          version: app.version,
+        }),
```
Comment (FabianLars) [inline src/build.ts]: same

File: src/utils.ts [hunk 3]
```diff
@@ -96,15 +96,14 @@ export function getAssetName(asset: Artifact, pattern?: string) {
     let arch = '';
     let dbg = '';
 
-    if (asset.ext === '.app.tar.gz' || asset.ext === '.app.tar.gz.sig') {
+    if ((asset.ext === '.app.tar.gz' || asset.ext === '.app.tar.gz.sig' || asset.ext === '' || asset.ext === '.exe') && !name.includes(asset.arch)) {
```
Comment (FabianLars) [inline src/utils.ts]: i think it makes more sense to add some switch to `Artifact` so we can immediately tell it's the binary

**Review by FabianLars — COMMENTED** [review]
Thanks for the PR so far!

I think this _must_ be behind a config though. We shouldn't just start uploading those files in every downstream repo, especially because the macos and linux binaries are basically useless standalone unless you use them to create some kind of bundle yourself.

Also, i wonder if this could mess up the latest.json generator on the windows side

File: src/build.ts (hunk 1 above)
Comment (jarjk) [reply src/build.ts]: alright, will do in a sec

**Comment by jarjk** [comment]
> Thanks for the PR so far!
> 
> I think this _must_ be behind a config though. We shouldn't just start uploading those files in every downstream repo, especially because the macos and linux binaries are basically useless standalone unless you use them to create some kind of bundle yourself.
> 
> Also, i wonder if this could mess up the latest.json generator on the windows side

Thanks for the rapid review!

~You're completely right, I'll create an input for this, with the name `uploadPlainBinary` or so?~ EDIT: added `uploadPlainBinary` to `input`s

It definitely does make sense to release these plain binaries, especially on macos and linux: first of all, any other form os macos artifact is tought to be corrupted by the os, and it can't be run (in our case, not sure it happens with other apps as well). with linux it's just so much easier to run the executable on eg. Arch Linux (btw), than first decompressing a `.deb` package and then doing so. In our case the app is pretty simple with only one icon added to the bundles, which doesn't really matter in the end for us.

I have absolutely no idea what a latest.json generator is though.

File: src/utils.ts (hunk 3 above)
Comment (jarjk) [reply src/utils.ts]: sure, or could we use the otherwise useless `Artifact.name`?

Comment (jarjk) [reply src/utils.ts]: kidding, I honestly think it's less of a burden to leave it as is though

**Comment by jarjk** [comment]
**NOTE:** I guessed it correctly, that a `bun|pnpm run build` is necessary after each commit, right?
or is it triggered by a CI on merge?

File: src/utils.ts (hunk 3 above)
Comment (FabianLars) [reply src/utils.ts]: > sure, or could we use the otherwise useless Artifact.name?

ah right, .name was added for a similar usecase before (not a fan of that either but i don't care enough to refactor the action again)

> kidding, I honestly think it's less of a burden to leave it as is though

less of a burden right now at least, but it'll probably get an issue at some point. i don't care about that enough either though so leave it as is if you want.

**Comment by FabianLars** [comment]
> It definitely does make sense to release these plain binaries (plus your context)

fair enough though that depends on the target audience then.

> I have absolutely no idea what a latest.json generator is though.

if you have the updater plugin configured, the action will create and upload a latest.json file serving as the endpoint for the updater. So with the generator i meant upload-version-json.ts which used to be very sensitive

> NOTE: I guessed it correctly, that a bun|pnpm run build is necessary after each commit, right?

correct

File: src/utils.ts (hunk 3 above)
Comment (jarjk) [reply src/utils.ts]: oh, I see. will leave it as is then

**Comment by jarjk** [comment]
> > I have absolutely no idea what a latest.json generator is though.
> 
> if you have the updater plugin configured, the action will create and upload a latest.json file serving as the endpoint for the updater. So with the generator i meant upload-version-json.ts which used to be very sensitive

Is there anything I could do to make sure it doesn't get crazy in that case?

**Comment by FabianLars** [comment]
if your test project doesn't have the updater set up already don't worry about it, i'll check it after merge (can't run that CI on forks)

**Comment by jarjk** [comment]
all right, thanks.

I guess the final `prettier --write` is run, and that CI check should pass now, sorry I didn't check README.md formatting as well...

**Comment by jarjk** [comment]
come on, could've documented how to open a PR, or made a `pre-commit` hook.

got it anyways I guess.

**Comment by jarjk** [comment]
anything else?

**Comment by jarjk** [comment]
thanks a lot for merging!
