### PR TITLE
fix: Correctly detect Arm AppImages

### LINKED ISSUE #798: Action fails to find appimage built on self-hosted aarch64 device
We're using this action with a self-hosted arm64 runner, to build a Linux .deb/appimage. The problem is that the appimage gets names *.aarch64.AppImage, but the action looks for an artifact names *.arm64.AppImage. 

https://github.com/meshtastic/network-management-client/actions/runs/9199973425/job/25305699131

### PR DESCRIPTION
**Pull request by FabianLars**
fixes #798 

Waiting for user to test the change

### CODE REVIEW

File: src/build.ts [hunk 1]
```diff
@@ -190,7 +190,11 @@ export async function buildProject(
         ? 'amd64'
         : arch === 'x32' || arch === 'i686'
           ? 'i386'
-          : arch;
+          : arch === 'arm' // TODO: Confirm this
+            ? 'arm'
```
Comment (FabianLars) [inline src/build.ts:194]: looks stupid but i'd rather have it listed considering that it's different than everything else
